-- MySQL Script generated by MySQL Workbench
-- Thu Apr 25 15:25:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecoroutedb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecoroutedb` DEFAULT CHARACTER SET utf8 ;
USE `ecoroutedb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoroutedb`.`users` ;

CREATE TABLE IF NOT EXISTS `ecoroutedb`.`users` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) BINARY NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gasstations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoroutedb`.`gasstations` ;

CREATE TABLE IF NOT EXISTS `ecoroutedb`.`gasstations` (
  `gasStationID` SMALLINT UNSIGNED NOT NULL,
  `gasStationLat` DECIMAL(10,7) NULL,
  `gasStationLong` DECIMAL(10,7) NULL,
  `fuelCompID` TINYINT NOT NULL,
  `fuelCompNormalName` VARCHAR(45) NOT NULL,
  `gasStationOwner` VARCHAR(128) NOT NULL,
  `ddID` VARCHAR(10) NOT NULL,
  `ddNormalName` VARCHAR(45) NOT NULL,
  `municipalityID` VARCHAR(10) NOT NULL,
  `municipalityNormalName` VARCHAR(45) NOT NULL,
  `countyID` VARCHAR(10) NOT NULL,
  `countyName` VARCHAR(64) NOT NULL,
  `gasStationAddress` VARCHAR(255) NULL,
  `phone1` CHAR(10) NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`gasStationID`),
  INDEX `fk_gasstations_users1_idx` (`username` ASC) ,
  CONSTRAINT `fk_gasstations_users1`
    FOREIGN KEY (`username`)
    REFERENCES `ecoroutedb`.`users` (`username`)
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pricedata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoroutedb`.`pricedata` ;

CREATE TABLE IF NOT EXISTS `ecoroutedb`.`pricedata` (
  `productID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `gasStationID` SMALLINT UNSIGNED NOT NULL,
  `fuelTypeID` TINYINT UNSIGNED NOT NULL,
  `fuelSubTypeID` TINYINT UNSIGNED NOT NULL,
  `fuelNormalName` VARCHAR(64) NOT NULL,
  `fuelName` VARCHAR(128) NOT NULL,
  `fuelPrice` DECIMAL(4,3) NOT NULL,
  `dateUpdated` TIMESTAMP NULL,
  `isPremium` TINYINT(1) NULL,
  PRIMARY KEY (`productID`),
  UNIQUE INDEX `unique_product` (`gasStationID` ASC, `fuelTypeID` ASC, `fuelSubTypeID` ASC) ,
  CONSTRAINT `fk_pricedata_gasstations`
    FOREIGN KEY (`gasStationID`)
    REFERENCES `ecoroutedb`.`gasstations` (`gasStationID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoroutedb`.`orders` ;

CREATE TABLE IF NOT EXISTS `ecoroutedb`.`orders` (
  `orderID` INT NOT NULL AUTO_INCREMENT,
  `productID` INT UNSIGNED NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `quantity` SMALLINT UNSIGNED NOT NULL,
  `when` TIMESTAMP NULL,
  PRIMARY KEY (`orderID`),
  INDEX `fk_orders_users1_idx` (`username` ASC) ,
  INDEX `fk_orders_pricedata1_idx` (`productID` ASC) ,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`username`)
    REFERENCES `ecoroutedb`.`users` (`username`),
  CONSTRAINT `fk_orders_pricedata1`
    FOREIGN KEY (`productID`)
    REFERENCES `ecoroutedb`.`pricedata` (`productID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
